# Welcome to Jekyll!

title: Amàlia GF
email: amgrefau@upv.es
description: > # this means to ignore newlines until "baseurl:"
   Website: <a href="https://amaliag0.github.io/">amaliag0.github.io</a><br><br><img src="https://raw.githubusercontent.com/amaliag0/amaliag0.github.io/master/images/profile.png" alt="MU"><br>
   Index: <a href="https://amaliag0.github.io/index">Website Contents</a>
baseurl: "" 
url: "" 

# Build settings
theme: jekyll-theme-minimal
