# Jekyll config file

title: En Línia
owner: amaliag0
email: am.aliegf@gmail.com # amgrefau@upv.es
description: Web personal d'Amàlia
   # this means to ignore newlines until "baseurl:"
   # <img src="images/dojocat.jpg" 
   #   alt="jo" style="width:10%;height:10%;">
   # <br><br><br>
   # <a href="https://amaliag0.github.io/">amaliag0.github.io</a>
   # https://raw.githubusercontent.com/amaliag0/amaliag0.github.io/master/images/profile.png
baseurl: "" 
url: "" 

# defaults:
#    -
#       scope: 
#          path: "content" # an empty string here means all files in the project
#          type: "page"
#       values:
#          layout: "default"

# Build settings
# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one