# Welcome to Jekyll!

title: Amàlia Gregori
email: amgrefau@upv.es
description: > # this means to ignore newlines until "baseurl:"
  twitter: <a href="https://twitter.com/am_aliag">@am_aliag</a><br>Website: <a href="https://amaliag0.github.io/">amaliag0.github.io</a><br>Company: <a href="http://www.ackcent.com/">Ackcent</a><br><br><img src="https://raw.githubusercontent.com/joanbono/joanbono.github.io/master/images/profile.png" alt="MU"><br>
baseurl: "" 
url: "" 

# Build settings
theme: jekyll-theme-minimal
